CREATE TABLE IF NOT EXISTS export_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  entity_type VARCHAR(50) NOT NULL,
  entity_id UUID,
  status VARCHAR(20) DEFAULT 'PENDING',
  storage_key TEXT,
  file_name TEXT,
  expires_at TIMESTAMP WITH TIME ZONE,
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  completed_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE export_jobs ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE export_jobs ADD COLUMN IF NOT EXISTS entity_type VARCHAR(50) NOT NULL DEFAULT 'unknown';
ALTER TABLE export_jobs ADD COLUMN IF NOT EXISTS entity_id UUID;
ALTER TABLE export_jobs ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'PENDING';
ALTER TABLE export_jobs ADD COLUMN IF NOT EXISTS storage_key TEXT;
ALTER TABLE export_jobs ADD COLUMN IF NOT EXISTS file_name TEXT;
ALTER TABLE export_jobs ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE export_jobs ADD COLUMN IF NOT EXISTS error_message TEXT;
ALTER TABLE export_jobs ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE export_jobs ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE;

CREATE INDEX IF NOT EXISTS idx_export_jobs_user_id ON export_jobs(user_id);
